---
- name: "Installing a package"
  hosts: all
  become: true
  tasks:
    - name: "Insatll nginx"
      yum:
        name:
          nginx
        state: latest

    - name: "create a file"
      file:
        path: /tmp/some_file.txt
        state: touch 
        
    - name: "check if service is stopped/disabled"
      service:
        name: nginx
        state: stopped
